# Generated by Django 4.2 on 2025-02-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(choices=[('study', '勉強'), ('work', '仕事'), ('private', 'プライベート'), ('other', 'その他')], max_length=100)),
            ],
        ),
    ]
